version: 2

jobs:
   ubuntu22:
     # Ubuntu 22
     docker:
       - image: ubuntu:22.04
     steps:
       - checkout
       - run:
          name: Dependencies
          command: |
              apt-get -q update -y
              DEBIAN_FRONTEND=noninteractive apt-get -q install -y zlib1g-dev m4 build-essential git terminfo bison flex wget libssl-dev libopenblas-dev python3 
       - run:
          name: Build
          command: |
              export ACT_HOME=`pwd`/install
              export PATH=$ACT_HOME/bin:$PATH
              mkdir install
              git submodule update --init --recursive
              ./build.sh

workflows:
   version: 2
   build:
     jobs:
        - ubuntu22
